import json
from pathlib import Path
import pandas as pd

import ast
from pathlib import Path

def load_stage2_configs(path="imp_stage2_configs.py"):
    text = Path(path).read_text()
    tree = ast.parse(text)

    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if getattr(target, "id", None) == "imp_stage2_configurations":
                    return ast.literal_eval(node.value)

    raise RuntimeError("Could not find imp_stage2_configurations")

imp_stage2_configurations = load_stage2_configs()

TOP_N = 5
DISTANCES = [32, 64]

INPUT = "imp_stage2_with_comparison.csv"
PLAN_OUT = "imp_stage3_plan.json"
CONFIG_OUT = "imp_stage3_configs.py"
RUN_OUT = "run_imp_stage3_multisim.py"

BENCHMARKS = {
    "simple_triad": {
        "binary": "benchmarks/simple_triad/simple_triad-m5.x",
        "args": ["1000000", "1"],
    },
    "matmult": {
        "binary": "benchmarks/matmult/matmult-m5.x",
        "args": ["1"],
    },
    "spmv": {
        "binary": "benchmarks/spmv/spmv-m5.x",
        "args": [],
    },
    "merge": {
        "binary": "benchmarks/merge/merge-m5.x",
        "args": ["x"],
    },
    "quick": {
        "binary": "benchmarks/quick/quick-m5.x",
        "args": ["x"],
    },
    "bfs": {
        "binary": "benchmarks/bfs/bfs-m5.x",
        "args": [],
    },
}


def sanitize(name):
    return (
        str(name)
        .replace("stage1:", "")
        .replace("stage2:", "")
        .replace(" ", "")
        .replace("-", "_")
        .replace("+", "p")
        .replace(".", "p")
    )


df = pd.read_csv(INPUT)

required = ["benchmark", "pf_level", "memory", "config", "speedup_vs_imp_default"]
missing = [c for c in required if c not in df.columns]
if missing:
    raise RuntimeError(f"Missing columns in {INPUT}: {missing}")

stage3_configs = {}
plan = {}

for (benchmark, pf_level, memory), sub in df.groupby(["benchmark", "pf_level", "memory"]):
    sub = sub.copy()

    # Remove default; Stage 3 is about extending tuned configs.
    sub = sub[sub["config"] != "default"]

    top = (
        sub.sort_values("speedup_vs_imp_default", ascending=False)
        .drop_duplicates(subset=["config"])
        .head(TOP_N)
    )

    case_key = f"{benchmark}|{pf_level}|{memory}"
    plan[case_key] = []

    for _, row in top.iterrows():
        base_name = row["config"]

        if base_name not in imp_stage2_configurations:
            print(f"WARNING: {base_name} not found in imp_stage2_configurations, skipping")
            continue

        base_params = dict(imp_stage2_configurations[base_name])

        for dist in DISTANCES:
            new_params = dict(base_params)
            new_params["streaming_distance"] = dist

            new_name = f"{sanitize(base_name)}_s{dist}"

            # If two cases generate the same config name with same params, reuse it.
            if new_name in stage3_configs and stage3_configs[new_name] != new_params:
                raise RuntimeError(f"Name collision for {new_name}")

            stage3_configs[new_name] = new_params
            plan[case_key].append(new_name)

# Remove duplicates within each case.
for k in plan:
    plan[k] = sorted(set(plan[k]))

Path(PLAN_OUT).write_text(json.dumps(plan, indent=2, sort_keys=True))

with open(CONFIG_OUT, "w") as f:
    f.write("from m5.objects import IndirectMemoryPrefetcher\n\n")
    f.write("# Auto-generated by make_imp_stage3_files.py\n")
    f.write("# Stage 3 tests whether sdist=32/64 improves over the top Stage 2 configs.\n\n")
    f.write("imp_stage3_configurations = {\n")
    for name, params in sorted(stage3_configs.items()):
        f.write(f'    "{name}": {repr(params)},\n')
    f.write("}\n\n")
    f.write(
'''def make_imp_stage3_prefetcher(config_name):
    params = dict(imp_stage3_configurations[config_name])

    # Safety restrictions that removed IMP PrefetchInfo::get panics.
    params.setdefault("on_read", True)
    params.setdefault("on_write", False)
    params.setdefault("on_data", True)
    params.setdefault("on_inst", False)

    params.setdefault("on_miss", True)
    params.setdefault("prefetch_on_access", False)
    params.setdefault("prefetch_on_pf_hit", False)

    class ConfiguredIMPPrefetcher(IndirectMemoryPrefetcher):
        def __init__(self):
            super().__init__(**params)

    return ConfiguredIMPPrefetcher
'''
    )

with open(RUN_OUT, "w") as f:
    f.write(
'''import os
import sys
import json

THIS_DIR = os.path.dirname(os.path.abspath(__file__))
if THIS_DIR not in sys.path:
    sys.path.insert(0, THIS_DIR)

from gem5.resources.resource import BinaryResource
from gem5.simulate.simulator import Simulator
from gem5.utils.multisim import multisim

from hardwares import (
    HWBoard,
    MyOutOfOrderCPU,
    MyClassicPrivateL1SharedL2CacheHierarchyBuild,
    DDR4,
    DDR4_2x,
)

from imp_stage3_configs import make_imp_stage3_prefetcher

multisim.set_num_processes(4)

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

BENCHMARKS = {
    "simple_triad": {
        "binary": "benchmarks/simple_triad/simple_triad-m5.x",
        "args": ["1000000", "1"],
    },
    "matmult": {
        "binary": "benchmarks/matmult/matmult-m5.x",
        "args": ["1"],
    },
    "spmv": {
        "binary": "benchmarks/spmv/spmv-m5.x",
        "args": [],
    },
    "merge": {
        "binary": "benchmarks/merge/merge-m5.x",
        "args": ["x"],
    },
    "quick": {
        "binary": "benchmarks/quick/quick-m5.x",
        "args": ["x"],
    },
    "bfs": {
        "binary": "benchmarks/bfs/bfs-m5.x",
        "args": [],
    },
}

MEMORIES = {
    "ddr4_1x": DDR4,
    "ddr4_2x": DDR4_2x,
}

with open("imp_stage3_plan.json") as f:
    STAGE3_PLAN = json.load(f)


def make_board(memory_name, pf_level, config_name):
    IMPPF = make_imp_stage3_prefetcher(config_name)

    if pf_level == "l1d":
        l1d_pf = IMPPF
        l2_pf = None
    elif pf_level == "l2":
        l1d_pf = None
        l2_pf = IMPPF
    else:
        raise ValueError(f"Unknown pf_level: {pf_level}")

    processor = MyOutOfOrderCPU(
        width=4,
        rob_size=128,
        num_int_regs=160,
        num_fpvec_regs=160,
        lsq_size=64,
    )

    memory = MEMORIES[memory_name]()

    cache_hierarchy = MyClassicPrivateL1SharedL2CacheHierarchyBuild(
        l1d_size="16KiB",
        l1d_assoc=8,
        l2_size="256KiB",
        l2_assoc=16,
        l1d_prefetcher=l1d_pf,
        l2_prefetcher=l2_pf,
    )

    return HWBoard(
        clk_freq="3GHz",
        processor=processor,
        memory=memory,
        cache_hierarchy=cache_hierarchy,
    )


def add_simulation(benchmark_name, pf_level, memory_name, config_name):
    benchmark_info = BENCHMARKS[benchmark_name]
    binary_path = os.path.join(PROJECT_ROOT, benchmark_info["binary"])

    if not os.path.exists(binary_path):
        raise FileNotFoundError(binary_path)

    board = make_board(memory_name, pf_level, config_name)

    board.set_se_binary_workload(
        BinaryResource(local_path=binary_path),
        arguments=benchmark_info["args"],
    )

    sim_id = f"{benchmark_name}_imp3_{config_name}_{pf_level}_{memory_name}"

    multisim.add_simulator(
        Simulator(
            board=board,
            id=sim_id,
        )
    )


for case_key, config_names in STAGE3_PLAN.items():
    benchmark_name, pf_level, memory_name = case_key.split("|")

    for config_name in config_names:
        add_simulation(benchmark_name, pf_level, memory_name, config_name)
'''
    )

num_runs = sum(len(v) for v in plan.values())

print(f"Wrote {CONFIG_OUT}")
print(f"Wrote {PLAN_OUT}")
print(f"Wrote {RUN_OUT}")
print(f"Unique Stage 3 configs: {len(stage3_configs)}")
print(f"Planned Stage 3 simulations: {num_runs}")
print()
for case, configs in sorted(plan.items()):
    print(f"{case}: {len(configs)} configs")